function mxFvEnhancer(){
'use strict';
if(window.__mxFv106)return;window.__mxFv106=true;
const $=x=>document.getElementById(x),T=v=>String(v??'').trim(),N=v=>{v=Number(v);return Number.isFinite(v)?v:0},U=v=>T(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' '),E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),K=v=>{try{return btoa(unescape(encodeURIComponent(U(v)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}catch(_){return U(v).replace(/[.#$\[\]\/]/g,'_')}};
const M='mx_fv_voice_muted_v1',S={o:[],om:new Map(),c:{},f:{},l:{},p:[],a:new Set(),wa:new Set(),id:'',sel:null,busy:false,last:0};
const cfg=()=>{try{return window.mxViewerGetCfg?.()||{}}catch(_){return{}}},br=()=>T(cfg().branch||window.mxFixedPrincipalBinding?.systemId||'HGAM').toUpperCase(),db=()=>T(cfg().db||cfg().firebaseUrl).replace(/\.json\/?$/i,'').replace(/\/+$/,'');
function url(p,q=false){if(!db())throw Error('Esperando conexión con Macroxel Hospital.');if(!p.startsWith('/'))p='/'+p;let u=new URL(db()+p+(p.endsWith('.json')?'':'.json'));if(q)u.searchParams.set('mx',Date.now());return u}
async function get(p){let r=await fetch(url(p,true),{cache:'no-store'});if(!r.ok)throw Error('Firebase HTTP '+r.status);return r.json().catch(()=>null)}
async function put(p,v){let r=await fetch(url(p),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(v),cache:'no-store'});if(!r.ok)throw Error('Firebase HTTP '+r.status);return r.json().catch(()=>true)}
async function patch(p,v){let r=await fetch(url(p),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(v),cache:'no-store'});if(!r.ok)throw Error('Firebase HTTP '+r.status);return r.json().catch(()=>true)}
async function ver(n){try{await put(`/sync_versions/${encodeURIComponent(br())}/${n}`,{v:Date.now(),updatedAt:new Date().toISOString(),source:'FARMACOVIGILANCIA'})}catch(_){}}
function who(){try{let u=JSON.parse(localStorage.getItem('mx_fv_user_session_v104')||'null')||{};return T(localStorage.getItem('mx_fv_responsible_v1')||u.username||u.name||u.fullName||localStorage.getItem('mx_fv_name_v1')||'Farmacovigilancia')}catch(_){return'Farmacovigilancia'}}
const muted=()=>localStorage.getItem(M)==='1';
function mute(v){localStorage.setItem(M,v?'1':'0');if(v)try{speechSynthesis.cancel()}catch(_){};paintMute()}
let nativeSpeak=null;try{if(speechSynthesis?.speak){nativeSpeak=speechSynthesis.speak.bind(speechSynthesis);speechSynthesis.speak=function(x){if(muted())return;if(/^Colectivo justificado pendiente de validaci[oó]n por farmacovigilancia/i.test(T(x?.text)))return;return nativeSpeak(x)}}}catch(_){}
function say(s){if(muted()||!s)return;try{let x=new SpeechSynthesisUtterance(s);x.lang='es-MX';x.rate=.92;(nativeSpeak||speechSynthesis.speak.bind(speechSynthesis))(x)}catch(_){}}
function paintMute(){let b=$('mxFvMute');if(b){b.textContent=muted()?'🔊 Activar voz':'🔇 Callar alertas';b.title=muted()?'Reactivar avisos por voz':'Silenciar todos los avisos por voz'}}
function protectSettings(){try{if(window.__mxFvSetProtect)return;window.__mxFvSetProtect=true;let pf=fetch.bind(window);window.fetch=function(i,n={}){try{let u=new URL(typeof i==='string'?i:i.url,location.href);if(U(n.method)==='PUT'&&u.pathname.endsWith(`/pharmacovigilance_settings/${encodeURIComponent(br())}.json`)&&Object.keys(S.l).length){let b=JSON.parse(n.body||'{}');if(b&&!b.antibioticDoseLimits)n={...n,body:JSON.stringify({...b,antibioticDoseLimits:S.l})}}}catch(_){}return pf(i,n)}}catch(_){}}

const items=o=>Array.isArray(o?.items)?o.items.filter(Boolean):(o?.items&&typeof o.items==='object'?Object.values(o.items).filter(Boolean):[]),ikeys=o=>Array.isArray(o?.items)?o.items.map((_,i)=>String(i)):(o?.items&&typeof o.items==='object'?Object.keys(o.items):[]),oid=o=>T(o?.id||o?.folioSolicitud||o?.folio),just=o=>U(o?.tipo||o?.tipo_doc).includes('JUSTIFICADO'),cancel=o=>/REJECT|CANCEL|NO SURTIDO/.test(U(o?.status||o?.estado)),done=o=>/^(FINALIZED|FINALIZADO|APPLIED|SURTIDO)$/.test(U(o?.status||o?.estado));
function valid(o){let s=U(o?.validacionFarmacovigilancia?.estado||o?.validacionFarmacovigilanciaEstado||(o?.farmacovigilanciaValidado?'VALIDADO':''));return !['PENDIENTE','PENDIENTE_AJUSTE'].includes(s)&&(s.includes('VALID')||o?.validacionFarmacovigilancia?.validado===true||o?.farmacovigilanciaValidado===true)}
const q=i=>Math.max(0,N(i?.cantidadSolicitadaAhora??i?.cantidadSolicitudActual??i?.cantidadPorRecibir??i?.cantidadRecibidaSolicitada??i?.cantidad24Horas??i?.qty??i?.cantidadSolicitada??i?.pzs??i?.cantidad)),tot=(i,o={})=>Math.max(0,N(i?.cantidadTratamientoTotal||i?.totalUnidadesTratamiento||o?.cantidadTratamientoTotal||o?.totalUnidadesTratamiento||i?.cantidadSolicitada)),prior=(i,o={})=>Math.max(0,N(i?.cantidadRecibidaAcumuladaAnterior),N(i?.cantidadRecibidaAcumulada),N(o?.cantidadRecibidaAcumuladaAnterior),N(o?.cantidadRecibidaAcumulada));
function dt(o){for(let v of [o?.createdAt,o?.requestedAt,o?.fechaSolicitud,o?.fechaIso,o?.fecha,o?.updatedAt]){let d=new Date(v||0);if(!isNaN(d)&&d.getFullYear()>2000)return d}return null}
function state(o){let id=oid(o),f=S.f[id],c=S.c[id],fs=U(f?.status),ms=U(o?.mobileStatus);if(fs==='APPLIED'||done(o))return['YA SURTIDO',false,'ok'];if(['PENDING_APPLY','PROCESSING'].includes(fs)||ms==='PENDING_APPLY')return['SURTIDO CAPTURADO · PENDIENTE DE APLICAR',false,'warn'];if(cancel(o))return['CERRADO / NO SURTIDO',false,'bad'];if(c&&new Date(c.expiresAt||0)>new Date())return['SURTIENDO',true,'warn'];let i=items(o)[0]||{},p=prior(i,o),t=tot(i,o);if(p>0&&(!t||p<t))return['SURTIDO PARCIAL · RESTANTE PENDIENTE',true,'warn'];return['SIN SURTIR',true,'info']}
const mid=i=>U(i?.clave||i?.medicamentoClave||i?.descripcion||i?.medicamento),mname=i=>T(i?.descripcion||i?.medicamento||i?.nombreMedicamento||i?.clave)||'Medicamento',pid=o=>U(o?.paciente||o?.nombrePaciente)?'N:'+U(o?.paciente||o?.nombrePaciente):(U(o?.expediente)?'E:'+U(o.expediente):'');
function same(a,b){let an=U(a?.paciente),bn=U(b?.paciente);if(an&&bn)return an===bn;return !!U(a?.expediente)&&U(a?.expediente)===U(b?.expediente)}
function parseDose(v){let m=T(v).replace(',','.').match(/([\d.]+)\s*(MCG|µG|UG|MG|G|PIEZA(?:S)?|PZ(?:S)?)/i);return[m?N(m[1]):0,m?T(m[2]).toUpperCase():'']}
const dose=(i,o)=>Math.max(0,N(i?.dosisIndicadaValor||o?.dosisIndicadaValor||parseDose(o?.dosisIndicada)[0])),unit=(i,o)=>T(i?.dosisUnidad||o?.dosisUnidad||parseDose(o?.dosisIndicada)[1]||'PIEZA').toUpperCase(),hours=(i,o)=>Math.max(0,N(i?.dosisCadaHoras||o?.dosisCadaHoras||((T(o?.dosisIndicada).match(/cada\s*(\d+(?:\.\d+)?)\s*h/i)||[])[1]))),days=(i,o)=>Math.max(0,N(i?.tiempoTratamientoDias||o?.tiempoTratamientoDias||((T(o?.tiempoTratamiento).match(/(\d+(?:\.\d+)?)\s*d/i)||[])[1])));
const mg=(v,u)=>U(u)==='G'?v*1000:(['MCG','UG','µG'].includes(U(u))?v/1000:v);
function strength(i,o){for(let r of [i?.concentracion,i?.strength,i?.concentracionMedicamento,i?.unidadMedidaDosis,i?.unidadMedida,i?.descripcion,i?.presentacion,i?.unidad,o?.concentracionMedicamento,o?.unidadMedidaDosis]){r=T(r).replace(',','.').replace(/GRAMOS?/ig,'G').replace(/MILIGRAMOS?/ig,'MG').replace(/MICROGRAMOS?/ig,'MCG');let m=r.match(/(\d+(?:\.\d+)?)\s*(MCG|µG|UG|MG|G)\b/i);if(m)return mg(N(m[1]),m[2])}return 0}
function calc(o,d,h,dys){let i=items(o)[0]||{},u=unit(i,o),da=Math.max(1,Math.ceil(24/Math.max(1,h))),adm=Math.max(1,Math.ceil((Math.max(1,dys)*24)/Math.max(1,h))),mode=U(i?.dosisModoCalculo||o?.dosisModoCalculo),piece=mode.includes('PIEZ')||/PIEZA|PZ/.test(U(u)),mass=['G','MG','MCG','UG','µG'].includes(U(u)),pa=0,need=false,s=strength(i,o);if(piece)pa=Math.max(1,Math.ceil(d));else if(s>0)pa=Math.max(1,Math.ceil(mg(d,u)/s-1e-10));else if(mass)need=true;else pa=Math.max(1,Math.ceil(d));let daily=need?0:pa*da,total=need?0:pa*adm,p=prior(i,o),rem=Math.max(0,total-p),extra=Math.max(0,Math.floor(N(i?.cantidadImpregnacionExtra)));return{u,adm,daily,total,p,rem,req:rem?Math.min(rem,daily+extra):0,old:q(i),ot:tot(i,o),need}}
const note=(e,m)=>T(e)?(T(e).includes(m)?T(e):T(e)+'\n'+m):m;

async function syncProfile(o,c,m,now){
 try{let b=encodeURIComponent(br()),all=await get(`/patient_catalog/${b}`).catch(()=>null);if(!all)return;let key=T(o.patientKey),p=key&&all[key]?all[key]:null,wn=U(o.paciente),wf=U(o.expediente);if(!p)for(let [k,x] of Object.entries(all)){if(x&&U(x.nombre||x.paciente)===wn&&(!wf||!U(x.expediente)||U(x.expediente)===wf)){key=k;p=x;break}}if(!p||!key)return;
 let raw=p.tratamientos,arr=Array.isArray(raw),en=arr?raw.map((v,i)=>[String(i),v]):Object.entries(raw||{}),want=mid(items(o)[0]||{}),f=en.find(([,x])=>mid(x)===want),tk=f?.[0]??(arr?String(en.length):K(want||Date.now())),x=f?.[1]||{},d=N($('mxFvDose')?.value),h=N($('mxFvHours')?.value),dy=N($('mxFvDays')?.value),nx={...x,clave:T(x.clave||items(o)[0]?.clave),medicamentoClave:T(x.medicamentoClave||items(o)[0]?.clave),medicamento:T(x.medicamento||mname(items(o)[0]||{})),dosisIndicada:`${d} ${c.u} CADA ${h} HORAS`,dosisIndicadaValor:d,dosisUnidad:c.u,dosisCadaHoras:h,tiempoTratamientoDias:dy,cantidad24Horas:c.daily,cantidadTratamientoTotal:c.total,totalUnidadesTratamiento:c.total,cantidadSolicitadaCalculada:c.total,cantidadRestante:c.rem,cantidadRecibidaAcumulada:Math.max(N(x.cantidadRecibidaAcumulada),c.p),nota:note(x.nota,m),ajustadoPorFarmacovigilancia:true,ajusteFarmacovigilanciaAt:now,updatedAt:now,updatedBy:who()},tr=arr?raw.slice():{...(raw||{})};if(arr)tr[Number(tk)]=nx;else tr[tk]=nx;
 await put(`/patient_catalog/${b}/${encodeURIComponent(key)}`,{...p,dosisIndicada:nx.dosisIndicada,dosisIndicadaValor:d,dosisUnidad:c.u,dosisCadaHoras:h,tiempoTratamientoDias:dy,cantidad24Horas:c.daily,cantidadTratamientoTotal:c.total,cantidadSolicitadaCalculada:c.total,cantidadRestante:c.rem,cantidadRecibidaAcumulada:Math.max(N(p.cantidadRecibidaAcumulada),c.p),tratamientos:tr,ajustadoPorFarmacovigilancia:true,ajusteFarmacovigilanciaAt:now,updatedAt:now,updatedBy:who()});await ver('patients')
 }catch(e){console.warn('[FV perfil]',e)}
}

function preview(){let o=S.om.get(S.id),b=$('mxFvQtyPreview'),msg=$('mxFvAdjustMsg');if(!o||!b)return;let d=N($('mxFvDose')?.value),h=N($('mxFvHours')?.value),dy=N($('mxFvDays')?.value);if(!d||!h||!dy){b.innerHTML='<small>Captura dosis, horas y días válidos.</small>';return}let c=calc(o,d,h,dy);if(c.need){b.innerHTML='<div class="mxwarn">No se pudo identificar la concentración por envase para convertir la dosis.</div>';if(msg)msg.textContent='Ajuste bloqueado hasta identificar la concentración del medicamento.';return}b.innerHTML=`<div><small>SOLICITUD ACTUAL</small><s>${c.old}</s> <b>→ ${c.req}</b></div><div><small>TRATAMIENTO TOTAL</small><s>${c.ot||'—'}</s> <b>→ ${c.total}</b></div>`;if(msg)msg.textContent=c.total<c.p?`No se puede bajar de ${c.p}; ya fue surtido.`:`Nuevo cálculo: ${c.daily} por 24 h · ${c.rem} restante(s).`}
async function save(){
 let id=S.id,btn=$('mxFvSaveAdjust'),msg=$('mxFvAdjustMsg');if(!id)return;if(btn)btn.disabled=true;
 try{let b=encodeURIComponent(br()),o=await get(`/service_orders/${b}/${encodeURIComponent(id)}`);if(!o)throw Error('El colectivo ya no está disponible.');o.id=id;let st=state(o);if(!st[1])throw Error(`El colectivo está en "${st[0]}" y ya no admite ajuste.`);let d=N($('mxFvDose')?.value),h=N($('mxFvHours')?.value),dy=N($('mxFvDays')?.value);if(!d||!h||!dy)throw Error('Dosis, horas y días deben ser mayores a cero.');let c=calc(o,d,h,dy);if(c.need)throw Error('No se identificó la concentración por envase.');if(c.total<c.p)throw Error(`El nuevo total (${c.total}) es menor a lo ya surtido (${c.p}).`);
 let raw=o.items,ks=ikeys(o),k=ks[0]??'0',i=items(o)[0]||{},now=new Date().toISOString(),w=who(),od=dose(i,o),oh=hours(i,o),ody=days(i,o),mark=`AJUSTADO POR FARMACOVIGILANCIA · Dosis ${od||'—'} → ${d} ${c.u} · Frecuencia c/${oh||'—'} h → c/${h} h · Días ${ody||'—'} → ${dy} · Cantidad ${c.old} → ${c.req}.`,ni={...i,dosisIndicada:`${d} ${c.u} CADA ${h} HORAS`,dosisIndicadaValor:d,dosisUnidad:c.u,dosisCadaHoras:h,tiempoTratamientoDias:dy,numeroAdministraciones:c.adm,cantidad24Horas:c.daily,cantidadReferencia24Horas:c.daily,totalUnidadesTratamiento:c.total,cantidadTratamientoTotal:c.total,cantidadSolicitadaCalculada:c.total,cantidadSolicitada:c.total,cantidadRestanteAntes:c.rem,cantidadSolicitadaAhora:c.req,cantidadSolicitudActual:c.req,cantidadPorRecibir:c.req,cantidadRecibidaSolicitada:c.req,cantidadSolicitadaAnterior:c.old,cantidadSolicitadaAjustada:c.req,calculadoPorTratamiento:true,ajustadoPorFarmacovigilancia:true,ajusteFarmacovigilanciaAt:now,ajusteFarmacovigilanciaPor:w,nota:note(i.nota,mark),notaJustificado:note(i.notaJustificado,mark),notaUsuario:note(i.notaUsuario,mark),observaciones:note(i.observaciones,mark)},nis=Array.isArray(raw)?raw.slice():{...(raw||{})};if(Array.isArray(raw))nis[Number(k)||0]=ni;else nis[k]=ni;
 let vf=o.validacionFarmacovigilancia||{},base=T(vf.nota||o.notaFarmacovigilancia||o.observacionFarmacovigilancia||o.nota),cn=note(base,mark),hist={...(o.historialAjustesFarmacovigilancia||{})},hk=K(now);hist[hk]={at:now,por:w,dosisAnterior:od,dosisNueva:d,unidad:c.u,horasAnterior:oh,horasNueva:h,diasAnterior:ody,diasNuevos:dy,cantidadAnterior:c.old,cantidadNueva:c.req,totalAnterior:c.ot,totalNuevo:c.total,estadoAlAjustar:st[0]};
 await patch(`/service_orders/${b}/${encodeURIComponent(id)}`,{items:nis,dosisModoCalculo:T(i.dosisModoCalculo||o.dosisModoCalculo),dosisIndicada:`${d} ${c.u} CADA ${h} HORAS`,dosisIndicadaValor:d,dosisUnidad:c.u,dosisCadaHoras:h,tiempoTratamiento:`${dy} días`,tiempoTratamientoDias:dy,numeroAdministraciones:c.adm,cantidad24Horas:c.daily,cantidadReferencia24Horas:c.daily,totalUnidadesTratamiento:c.total,cantidadTratamientoTotal:c.total,totalTratamientoSolicitado:c.total,totalPiezas:c.req,cantidadRestanteAntes:c.rem,cantidadSolicitadaAhora:c.req,cantidadSolicitudActual:c.req,cantidadPorRecibir:c.req,cantidadRecibidaSolicitada:c.req,nota:note(o.nota,mark),notaJustificado:note(o.notaJustificado,mark),notaUsuario:note(o.notaUsuario,mark),observaciones:note(o.observaciones,mark),observacionesColectivo:note(o.observacionesColectivo,mark),notaFarmacovigilancia:cn,observacionFarmacovigilancia:cn,validacionFarmacovigilancia:{...vf,validado:false,estado:'PENDIENTE_AJUSTE',nota:cn,ajustadoAt:now,ajustadoPor:w},farmacovigilanciaValidado:false,validacionFarmacovigilanciaEstado:'PENDIENTE_AJUSTE',ajustadoPorFarmacovigilancia:true,ajusteFarmacovigilanciaAt:now,ajusteFarmacovigilanciaPor:w,historialAjustesFarmacovigilancia:hist,revision:Math.max(0,N(o.revision))+1,revisionKind:'AJUSTE_FARMACOVIGILANCIA',revisionUpdatedAt:now,revisionUpdatedBy:w,updatedAt:now});
 await put(`/pharmacovigilance_audit/${b}/ajustes_tratamiento/${encodeURIComponent(id)}/${hk}`,{orderId:id,folio:T(o.folioSolicitud||o.folio),paciente:T(o.paciente),expediente:T(o.expediente),clave:T(i.clave),medicamento:mname(i),...hist[hk],nota:mark});await ver('orders');await syncProfile(o,c,mark,now);if(msg)msg.textContent='✓ Ajuste guardado. El colectivo queda pendiente de validación por Farmacovigilancia.';try{dispatchEvent(new CustomEvent('mx-viewer-refresh-now',{detail:{reason:'AJUSTE_FARMACOVIGILANCIA',force:true}}))}catch(_){}await refresh(true);setTimeout(()=>editor(id),150)
 }catch(e){if(msg)msg.textContent='❌ '+(e.message||e)}finally{if(btn)btn.disabled=false}
}

function seven(o,i){let l=S.l[K(mid(i))]||S.l[K(i?.clave)],max=N(l?.max7Dias);if(!max)return'';let cut=Date.now()-604800000,sum=0,p=pid(o),m=mid(i);for(let x of S.o){if(cancel(x)||pid(x)!==p||(dt(x)?.getTime()||0)<cut)continue;for(let z of items(x))if(mid(z)===m)sum+=q(z)}return sum>max?`<div class="mxwarn">⚠ <b>PRECAUCIÓN PEDIDO SUPERA LO ESTABLECIDO</b><br>${E(o.paciente||'Paciente')} · ${E(mname(i))}<br>Máximo 7 días: <b>${max}</b> · Solicitado: <b>${sum}</b></div>`:`<div class="mxok">✓ Control 7 días: ${sum} / ${max}</div>`}
function editor(force=''){let m=$('fvJustModal'),med=$('fvJustModalMedicine');if(!m||m.classList.contains('hidden')||!med)return;let sub=T($('fvJustModalSub')?.textContent),id=force||[...S.om].find(([k,o])=>k===sub||T(o.folioSolicitud||o.folio)===sub)?.[0]||S.id,o=S.om.get(id);if(!o)return;S.id=id;let x=$('mxFvAdjustment');if(!x){x=document.createElement('div');x.id='mxFvAdjustment';med.after(x)}let i=items(o)[0]||{},st=state(o),p=prior(i,o),tt=tot(i,o),pct=tt?Math.min(100,Math.round(p/tt*100)):0;x.innerHTML=`<div class="mxhead"><b>AJUSTE DE TRATAMIENTO</b><small>Editable mientras el colectivo no esté aplicado.</small></div><div class="mxprog"><span class="${st[2]}">${E(st[0])}</span><b>${tt?`${p} / ${tt}`:`Previo ${p}`}</b><i><em style="width:${pct}%"></em></i><small>${tt?`${pct}% surtido · ${Math.max(0,tt-p)} restante(s)`:''}</small></div>${seven(o,i)}<div class="mxgrid"><label>DOSIS<input id="mxFvDose" type="number" min=".001" step="any" value="${E(dose(i,o)||'')}" ${st[1]?'':'disabled'}><small>${E(unit(i,o))}</small></label><label>CADA CUÁNTAS HORAS<input id="mxFvHours" type="number" min="1" value="${E(hours(i,o)||'')}" ${st[1]?'':'disabled'}></label><label>DÍAS DE TRATAMIENTO<input id="mxFvDays" type="number" min="1" value="${E(days(i,o)||'')}" ${st[1]?'':'disabled'}></label></div><div id="mxFvQtyPreview" class="mxqty"></div><div id="mxFvAdjustMsg" class="mxmsg">${st[1]?'Modifica y revisa la nueva cantidad.':'Este estado ya no permite modificar.'}</div><button id="mxFvSaveAdjust" class="btn good" ${st[1]?'':'disabled'}>💾 Guardar ajuste de tratamiento</button>`;['mxFvDose','mxFvHours','mxFvDays'].forEach(k=>$(k)?.addEventListener('input',preview));$('mxFvSaveAdjust')?.addEventListener('click',save);preview()}

function over(){let out=[],cut=Date.now()-604800000;for(let l of Object.values(S.l)){let max=N(l?.max7Dias);if(!max)continue;let g=new Map;for(let o of S.o){if(cancel(o)||(dt(o)?.getTime()||0)<cut)continue;for(let i of items(o)){if(!(U(i.clave)===U(l.clave)||(U(i.descripcion)===U(l.descripcion)&&U(l.descripcion))))continue;let p=pid(o);if(!p)continue;let x=g.get(p)||{sum:0,patient:T(o.paciente)||T(o.expediente)||'Paciente',medicine:mname(i)};x.sum+=q(i);g.set(p,x)}}for(let x of g.values())if(x.sum>max)out.push({...x,max,clave:l.clave,sig:`${x.patient}|${l.clave||l.descripcion}|${max}|${x.sum}`})}return out}
function warn(){let a=over(),now=new Set(a.map(x=>x.sig));for(let x of [...S.wa])if(!now.has(x))S.wa.delete(x);for(let x of a)if(!S.wa.has(x.sig)){S.wa.add(x.sig);say(`Precaución. Pedido supera lo establecido. Paciente ${x.patient}. Medicamento ${x.medicine}. Máximo ${x.max} en siete días. Solicitado acumulado ${x.sum}.`)}renderAlerts(a)}
function pending(){let n=new Date(),p=S.o.filter(o=>{let d=dt(o);return just(o)&&d&&d.toDateString()===n.toDateString()&&!cancel(o)&&!done(o)&&!valid(o)}),ids=new Set(p.map(oid));for(let x of [...S.a])if(!ids.has(x))S.a.delete(x);for(let o of p){let id=oid(o);if(!id||S.a.has(id))continue;S.a.add(id);let meds=[...new Set(items(o).map(mname))],others=S.o.filter(x=>oid(x)!==id&&just(x)&&!cancel(x)&&!done(x)&&same(o,x)),om=[...new Set(others.flatMap(x=>items(x).map(mname)))],msg=`Colectivo justificado pendiente de validación por farmacovigilancia. Paciente ${T(o.paciente)||'paciente'}. Medicamento solicitado ${meds.join(', ')||'sin descripción'}.`;if(others.length)msg+=` Atención. El paciente ya tiene ${others.length} ${others.length===1?'colectivo abierto':'colectivos abiertos'}${om.length?' con '+om.join(', '):''}.`;say(msg);let t=$('fvJustVoiceToast'),tx=$('fvJustVoiceText');if(t&&tx){tx.textContent=`${T(o.paciente)||'Paciente'} · ${meds.join(', ')}${others.length?` · ⚠ ${others.length} abierto(s): ${om.join(', ')}`:''}`;t.classList.add('show');t.dataset.fvOrder=id;t.onclick=()=>{t.classList.remove('show');let nav=document.querySelector('.nav button[data-view="justifiedValidation"]')||[...document.querySelectorAll('.nav button')].find(b=>/validaci/i.test(b.textContent));nav?.click();setTimeout(()=>document.querySelector(`[data-fv-order="${id.replace(/"/g,'\\"')}"]`)?.click(),100)};setTimeout(()=>{if(t.dataset.fvOrder===id)t.classList.remove('show')},10000)}}}
function cards(){document.querySelectorAll('[data-fv-order]').forEach(b=>{let o=S.om.get(T(b.dataset.fvOrder));if(!o)return;let x=b.querySelector('.mxcardstate');if(!x){x=document.createElement('small');x.className='mxcardstate';b.append(x)}x.textContent='Avance: '+state(o)[0]})}

async function products(force=false){if(S.p.length&&!force)return;let r=await get(`/cpm_catalog/${encodeURIComponent(br())}/items`).catch(()=>null),m=new Map;for(let x of (Array.isArray(r)?r:Object.values(r||{}))){let c=T(x?.clave),d=T(x?.descripcion);if(c||d)m.set(U(c||d),{clave:c,descripcion:d})}for(let o of S.o)for(let i of items(o))m.set(U(i.clave||i.descripcion),{clave:T(i.clave),descripcion:mname(i)});S.p=[...m.values()].sort((a,b)=>a.clave.localeCompare(b.clave,'es'))}
function results(){let qy=U($('mxFvDoseSearch')?.value),b=$('mxFvDoseResults');if(!b)return;if(qy.length<2){b.innerHTML='';return}let r=S.p.filter(x=>U(x.clave+' '+x.descripcion).includes(qy)).slice(0,30);b.innerHTML=r.map((x,i)=>`<button data-i="${i}"><b>${E(x.clave||'SIN CLAVE')}</b><span>${E(x.descripcion)}</span></button>`).join('')||'<small>Sin coincidencias.</small>';b.querySelectorAll('button').forEach((x,i)=>x.onclick=()=>select(r[i]))}
function select(p){S.sel=p;let b=$('mxFvDoseSelected'),old=Object.values(S.l).find(x=>U(x.clave)===U(p.clave)||(!p.clave&&U(x.descripcion)===U(p.descripcion)));b.classList.remove('hidden');b.innerHTML=`<b>${E(p.clave||'SIN CLAVE')}</b><span>${E(p.descripcion)}</span><label>CANTIDAD MÁXIMA A SOLICITAR EN 7 DÍAS<input id="mxFvDoseMax" type="number" min="1" value="${N(old?.max7Dias)||''}"></label><button id="mxFvDoseSave" class="btn good">Guardar parámetro</button><small id="mxFvDoseSaveMsg">Se configura una vez y permanece guardado.</small>`;$('mxFvDoseSave').onclick=saveLimit}
async function saveLimit(){let p=S.sel,max=Math.floor(N($('mxFvDoseMax')?.value)),m=$('mxFvDoseSaveMsg');if(!p||max<1){m.textContent='Captura una cantidad mayor a cero.';return}try{let r={clave:T(p.clave),descripcion:T(p.descripcion),max7Dias:max,activo:true,updatedAt:new Date().toISOString(),updatedBy:who()},k=K(p.clave||p.descripcion);await put(`/pharmacovigilance_settings/${encodeURIComponent(br())}/antibioticDoseLimits/${k}`,r);S.l[k]=r;await ver('pharmacovigilance');m.textContent='✓ Parámetro guardado.';renderLimits();warn()}catch(e){m.textContent='❌ '+e.message}}
async function del(k){if(!confirm('¿Eliminar este parámetro?'))return;await put(`/pharmacovigilance_settings/${encodeURIComponent(br())}/antibioticDoseLimits/${encodeURIComponent(k)}`,null);delete S.l[k];await ver('pharmacovigilance');renderLimits()}
function renderLimits(){let b=$('mxFvDoseLimits');if(!b)return;let r=Object.entries(S.l).filter(([,x])=>x&&x.activo!==false);b.innerHTML=r.map(([k,x])=>`<div class="mxlim"><div><b>${E(x.clave||'SIN CLAVE')}</b><span>${E(x.descripcion)}</span></div><strong>Máx. 7 días: ${E(x.max7Dias)}</strong><div><button class="btn secondary sm" data-e="${E(k)}">Editar</button> <button class="btn secondary sm" data-d="${E(k)}">Eliminar</button></div></div>`).join('')||'<div class="empty">Aún no hay parámetros.</div>';b.querySelectorAll('[data-e]').forEach(x=>x.onclick=()=>{let r=S.l[x.dataset.e];select({clave:r.clave,descripcion:r.descripcion})});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=()=>del(x.dataset.d))}
function renderAlerts(a=over()){let b=$('mxFvDoseAlerts');if(b)b.innerHTML=a.map(x=>`<div class="mxalert"><b>⚠ PRECAUCIÓN PEDIDO SUPERA LO ESTABLECIDO</b><span>${E(x.patient)} · ${E(x.medicine)}</span><small>Máximo 7 días: ${x.max} · Solicitado: ${x.sum}</small></div>`).join('')||'<div class="notice ok">Sin solicitudes por encima del parámetro.</div>'}

function mount(){
 if(!$('mxFvMute')){let h=document.querySelector('.top-actions,.toolbar,.topbar')||document.body,b=document.createElement('button');b.id='mxFvMute';b.className='btn secondary sm';b.onclick=()=>mute(!muted());h.append(b);paintMute()}
 if(!$('view-mxFvDoseControl')){let nav=document.querySelector('.nav'),v=[...document.querySelectorAll('.view')];if(nav&&v.length){let b=document.createElement('button');b.textContent='💊 Control antibiótico dosis';b.onclick=async()=>{nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('view-mxFvDoseControl').classList.remove('hidden');await products();renderLimits();renderAlerts()};nav.append(b);let s=document.createElement('section');s.id='view-mxFvDoseControl';s.className='view hidden';s.innerHTML=`<div class="card"><div class="section-head"><div><h2>💊 CONTROL ANTIBIOTICO DOSIS</h2><div class="sub">Cantidad máxima acumulada a solicitar por paciente y medicamento en 7 días.</div></div><button id="mxFvDoseReload" class="btn secondary sm">Actualizar</button></div><div class="mxcontrol"><div><div class="field"><label>BUSCAR POR CLAVE O NOMBRE</label><input id="mxFvDoseSearch" placeholder="Clave o nombre del medicamento"></div><div id="mxFvDoseResults" class="mxres"></div><div id="mxFvDoseSelected" class="mxselected hidden"></div></div><div><h3>Parámetros establecidos</h3><div id="mxFvDoseLimits"></div></div></div></div><div class="card"><h3>⚠ Alertas de los últimos 7 días</h3><div id="mxFvDoseAlerts"></div></div>`;v.at(-1).after(s);$('mxFvDoseSearch').oninput=results;$('mxFvDoseReload').onclick=async()=>{await refresh(true);await products(true);renderLimits();renderAlerts()}}}
 let m=$('fvJustModal');if(m&&!m.dataset.mx106){m.dataset.mx106='1';new MutationObserver(()=>{if(!m.classList.contains('hidden'))setTimeout(()=>editor(),30);else S.id=''}).observe(m,{attributes:true,attributeFilter:['class'],childList:true,subtree:true});document.addEventListener('click',e=>{let x=e.target.closest?.('[data-fv-order]');if(x){S.id=T(x.dataset.fvOrder);setTimeout(()=>editor(S.id),70)}},true)}
}
function css(){if($('mxFv106Css'))return;let s=document.createElement('style');s.id='mxFv106Css';s.textContent=`#mxFvMute{white-space:nowrap}.mxhead{border-top:2px solid #d8e5f0;margin-top:12px;padding-top:11px}.mxhead b,.mxhead small{display:block}.mxhead b{color:#0b4f7d}.mxhead small,.mxmsg{color:#64748b;font-size:11px}.mxprog{border:1px solid #d8e5f0;border-radius:12px;padding:9px;margin:8px 0}.mxprog>span{display:inline-block;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:900}.mxprog .ok{background:#dcfce7;color:#166534}.mxprog .warn{background:#fff7ed;color:#9a3412}.mxprog .bad{background:#fee2e2;color:#991b1b}.mxprog .info{background:#e0f2fe;color:#075985}.mxprog>b{float:right}.mxprog i{display:block;height:7px;background:#e2e8f0;border-radius:9px;margin:8px 0 4px;overflow:hidden}.mxprog em{display:block;height:100%;background:#2563eb}.mxgrid,.mxqty,.mxcontrol{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mxgrid label{font-size:10px;font-weight:900;color:#49617f}.mxgrid input,.mxselected input{width:100%;border:1px solid #cadbea;border-radius:10px;padding:9px;margin-top:4px}.mxqty{grid-template-columns:1fr 1fr;margin:8px 0}.mxqty>div{border:1px solid #d8e5f0;border-radius:10px;padding:8px}.mxqty small{display:block}.mxqty s{color:#b91c1c;font-size:18px;font-weight:900}.mxqty b{color:#15803d;font-size:19px;margin-left:7px}.mxwarn,.mxok{border-radius:10px;padding:8px;margin:8px 0;font-size:11px}.mxwarn{background:#fff7ed;border:1px solid #fdba74;color:#9a3412}.mxok{background:#ecfdf5;color:#166534}.mxmsg{padding:6px 0}.mxcardstate{display:block;color:#0b4f7d;font-weight:900;margin-top:5px}.mxcontrol{grid-template-columns:1.05fr .95fr}.mxres{max-height:280px;overflow:auto;margin-top:5px}.mxres button{width:100%;display:grid;grid-template-columns:100px 1fr;text-align:left;border:1px solid #d8e5f0;background:#fff;border-radius:9px;padding:7px;margin-bottom:4px}.mxselected{border:1px solid #bfdbfe;background:#eff6ff;border-radius:12px;padding:10px;margin-top:8px}.mxselected b,.mxselected span,.mxselected label,.mxselected small{display:block}.mxlim{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:center;border:1px solid #d8e5f0;border-radius:10px;padding:8px;margin-bottom:6px}.mxlim b,.mxlim span{display:block}.mxlim span,.mxlim strong{font-size:11px}.mxalert{background:#fff1f2;border:1px solid #fecaca;color:#9f1239;border-radius:10px;padding:9px;margin-top:6px}.mxalert b,.mxalert span,.mxalert small{display:block}@media(max-width:760px){.mxgrid,.mxqty,.mxcontrol,.mxlim{grid-template-columns:1fr}}`;document.head.append(s)}
async function refresh(force=false){if(S.busy||!db()||(!force&&Date.now()-S.last<4000))return;S.busy=true;try{let b=encodeURIComponent(br()),[o,c,f,l]=await Promise.all([get(`/service_orders/${b}`).catch(()=>null),get(`/service_order_claims/${b}`).catch(()=>null),get(`/service_order_fulfillments/${b}`).catch(()=>null),get(`/pharmacovigilance_settings/${b}/antibioticDoseLimits`).catch(()=>null)]);S.o=Object.entries(o||{}).filter(([,x])=>x&&typeof x==='object').map(([id,x])=>({id,...x}));S.om=new Map(S.o.map(x=>[oid(x),x]));S.c=c||{};S.f=f||{};S.l=l||{};S.last=Date.now();pending();warn();cards();if(S.id&&!$('fvJustModal')?.classList.contains('hidden'))editor(S.id);renderLimits();renderAlerts()}finally{S.busy=false}}
function boot(){protectSettings();css();mount();setTimeout(()=>refresh(true),1200);setInterval(()=>{if(!document.hidden)refresh(false)},10000);addEventListener('mx-viewer-refresh-now',()=>setTimeout(()=>refresh(true),200));addEventListener('mx-viewer-binding-updated',()=>setTimeout(()=>{S.p=[];refresh(true)},300));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
}